openapi: 3.0.0
info:
  title: Aura Interview
  version: 1.0.0
servers:
  - url: https://0gq2qt7zjb.execute-api.us-east-1.amazonaws.com
paths:
  /prod/zips:
    get:
      tags:
        - default
      summary: Get Zips
      parameters:
        - name: zip
          in: query
          schema:
            type: integer
          example: '123456'
        - name: type
          in: query
          schema:
            type: string
          example: STANDARD
        - name: primary_city
          in: query
          schema:
            type: string
          example: Seymour
        - name: country
          in: query
          schema:
            type: string
          example: US
        - name: area_codes
          in: query
          schema:
            type: integer
          example: '413'
        - name: coordinates
          in: query
          schema:
            type: number
          example: 41.93,-72.97
        - name: limit
          in: query
          schema:
            type: integer
          example: '5'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
